apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-server
  labels:
    app: ci
spec:
  selector:
    matchLabels:
      app: ci
  template:
    metadata:
      labels:
        app: ci
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
      serviceAccountName: builder
      containers:
      - name: ci-server
        image: <<image_path>>
        volumeMounts:
        - name: tmp
          mountPath: /.kube
        env:
        - name: OAUTH_TOKEN
          value: <<token>>
        - name: GITHUB_USER
          value: <<user>>
        - name: ORGANIZATION
          value: redhat-service-assurance
        - name: WEBHOOK_PROXY
          value: <<url>>
        ports:
        - containerPort: 3000
      initContainers:
      - name: kube-config
        image: busybox
        command: ['/bin/sh', '-c', 'cp /tmp/config /.kube/']
        volumeMounts:
        - name: tmp
          mountPath: /.kube
        - name: kube-config
          mountPath: /tmp/
      volumes:
      - name: kube-config
        secret:
          secretName: kube-config
      - name: tmp
        emptyDir: {}
